langname = {"af":"Afrikaans",
"ar":"Arabic",
"bg":"Bulgarian",
"bn":"Bengali",
"ca":"Catalan",
"cs":"Czech",
"cy":"Welsh",
"da":"Danish",
"de":"German",
"el":"Greek",
"en":"English",
"es":"Spanish",
"et":"Estonian",
"fi":"Finnish",
"fr":"French",
"gu":"Gujarathi",
"he":"Hebrew",
"hi":"Hindi",
"hr":"Croatian",
"hu":"Hungarian",
"id":"Indonesian",
"it":"Italian",
"ja":"Japanese",
"kn":"Kannada",
"ko":"Korean",
"lt":"Lithuanian",
"lv":"Latvian",
"mk":"Macedonian",
"ml":"Malayalam",
"mr":"Marathi",
"ne":"Nepali",
"nl":"Dutch",
"no":"Norwegian",
"pa":"Punjabi",
"pl":"Polish",
"pt":"Portugese",
"ro":"Romanian",
"ru":"Russian",
"sk":"Slovak",
"sl":"Slovenian",
"so":"Somalia",
"sq":"Albanian",
"sv":"Swedish",
"sw":"Swahili",
"ta":"Tamil",
"te":"Telugu",
"th":"Thai",
"tl":"Tagalog",
"tr":"Turkish",
"uk":"Ukrainian",
"ur":"Urdu",
"vi":"Vietnamese",
"zh-cn":"Classical Chinese",
"zh-tw":"Traditional Chinese"
}


from langdetect import detect

a = raw_input("Enter text [Longer text = better prediction] :")
print langname[detect(a)]
